<a href="https://colab.research.google.com/github/nanduk1296/Python_Projects/blob/main/Python_DA_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python DA Assignment1

In [2]:
import numpy as np


1. Create a 1D NumPy Array:

In [3]:
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print("Week 1 Temperatures:")
print(temperatures_w1)

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


2. Inspection and Properties:

In [5]:
print("\n--- Inspection and Properties ---")
print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)


--- Inspection and Properties ---
Shape: (7,)
Data Type: float64
Number of Elements: 7


3. Array Operations:

In [6]:
fahrenheit = (temperatures_w1 * 9/5) + 32
print("\n--- Celsius to Fahrenheit ---")
print(fahrenheit)
# Maximum, Minimum and Mean Temperature
print("\n--- Temperature Statistics ---")
print("Maximum Temperature:", np.max(temperatures_w1))
print("Minimum Temperature:", np.min(temperatures_w1))
print("Mean Temperature:", np.mean(temperatures_w1))


--- Celsius to Fahrenheit ---
[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

--- Temperature Statistics ---
Maximum Temperature: 26.1
Minimum Temperature: 20.8
Mean Temperature: 23.542857142857144


4. Array Slicing and Indexing:

In [7]:
print("\n--- Array Slicing ---")

print("First Three Days:")
print(temperatures_w1[:3])

print("\nWeekend Temperatures:")
print(temperatures_w1[-2:])

print("\nMiddle Three Days:")
print(temperatures_w1[2:5])


--- Array Slicing ---
First Three Days:
[22.5 25.3 20.8]

Weekend Temperatures:
[24.8 21.9]

Middle Three Days:
[20.8 23.4 26.1]


Step 5: Create a 2D Array

In [9]:
temperatures = np.array([
[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9], # Week 1
[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] # Week 2
])
print("\n--- 2D Temperature Array ---")
print(temperatures)



--- 2D Temperature Array ---
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


Step 6: Inspect and Slice the 2D Array

In [10]:
print("\n--- 2D Array Properties ---")
print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

# Extract temperatures for each week
print("\nWeek 1 Temperatures:")
print(temperatures[0])
print("\nWeek 2 Temperatures:")
print(temperatures[1])

# Extract weekends (last two days) for both weeks
print("\nWeekend Temperatures for Both Weeks:")
print(temperatures[:, -2:])


--- 2D Array Properties ---
Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14

Week 1 Temperatures:
[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

Week 2 Temperatures:
[19.2 22.5 21.3 24.  23.5 22.8 20.1]

Weekend Temperatures for Both Weeks:
[[24.8 21.9]
 [22.8 20.1]]


Pandas Series:
1. Creating Pandas Series:

In [11]:
import pandas as pd


marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print("Marks Series:")
print(marks)

Marks Series:
Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


2. Indexing and Slicing:

In [12]:

# Access the mark of the 1st rank student using integer index position
print("1st Rank Student Mark:", marks[0])

# Retrieve the marks of the top 3 ranks using loc
print("\nTop 3 Ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# Retrieve the mark of the 3rd rank student using iloc
print("\n3rd Rank Student Mark:")
print(marks.iloc[2])

# Filter ranks where marks are greater than 90
print("\nMarks Greater Than 90:")
print(marks[marks > 90])

1st Rank Student Mark: 95

Top 3 Ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd Rank Student Mark:
89

Marks Greater Than 90:
Rank1    95
Rank2    92
dtype: int64


/tmp/ipykernel_2157/2512422914.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print("1st Rank Student Mark:", marks[0])


3. Manipulating Series:

In [13]:
# Modify the mark of the 1st rank student to 100
marks['Rank1'] = 100

print("After Updating Rank1:")
print(marks)

# Remove the entry corresponding to the last rank
marks = marks.drop('Rank5')

print("\nAfter Removing Rank5:")
print(marks)

# Compute CGPA by dividing each mark by 10
cgpa = marks / 10

print("\nCGPA:")
print(cgpa)

After Updating Rank1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After Removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


Pandas DataFrame:
1. Creating Pandas DataFrame:

In [14]:
# Create the DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# Display the DataFrame
print("Transactions DataFrame:")
print(transactions)

Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


2. Data Exploration:

In [15]:
# Display the DataFrame
print("Transactions DataFrame:")
print(transactions)

# Head
print("\nFirst 5 Rows:")
print(transactions.head())

# Tail
print("\nLast 5 Rows:")
print(transactions.tail())

# Shape
print("\nShape of DataFrame:")
print(transactions.shape)

# Column Names
print("\nColumn Names:")
print(transactions.columns)

# Data Types
print("\nData Types:")
print(transactions.dtypes)

# Display only ProductCategory and Amount columns
print("\nProductCategory and Amount Columns:")
print(transactions[['ProductCategory', 'Amount']])

# Retrieve the last 3 columns using iloc
print("\nLast 3 Columns:")
print(transactions.iloc[:, -3:])

# Filter rows where Region is North and Amount > 200
print("\nTransactions in North Region with Amount > 200:")
print(transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
])

# Value counts for ProductCategory
print("\nProduct Category Counts:")
print(transactions['ProductCategory'].value_counts())

# Unique values in Region
print("\nUnique Regions:")
print(transactions['Region'].unique())

# Group by Region and find mean Amount
print("\nAverage Amount by Region:")
print(transactions.groupby('Region')['Amount'].mean())

Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

First 5 Rows:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 Rows:
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   

3. Manipulating the DataFrame:

In [16]:
# Modify the Amount for TransactionID 102 to 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

print("After Updating Amount for TransactionID 102:")
print(transactions)

# Add a new column 'Discount' (10% of Amount)
transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter Adding Discount Column:")
print(transactions)

# Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

print("\nAfter Removing TransactionID 109:")
print(transactions)

# Delete the Discount column
transactions = transactions.drop('Discount', axis=1)

print("\nAfter Removing Discount Column:")
print(transactions)

After Updating Amount for TransactionID 102:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After Adding Discount Column:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250 